exp_name: rev_util_verifiability#qwen3_8b#ft#label_only#rail#on_label_only#seed_42
model_name: model/Qwen3-8B
adapter: checkpoints/training-8B/rev_util_verifiability/label_only
train_seed: 42
dataset_file: data/rev_util_verifiability/label_only/test_label_only.jsonl
train_config: configs/training/training-8B/rev_util_verifiability/label_only.yaml
inference_mode: rail
output_path: outputs/evaluations/evaluation-8b
max_model_len: 8192
max_tokens: 1
temp: 0
top_p: 1.0
seed: 42
rollout: 1
batch_size: 64
gpu_memory_utilization: 0.9
merge_cache: /root/autodl-tmp/merged_qwen8b
merge_retention_days: 0
enable_thinking: false
